controllers/home.py
from flask import Blueprint, request, render_template, redirect, url_for

from services.language import change_lang

from controllers.damage import damage_blueprint
from controllers.document import document_blueprint
from controllers.user import user_blueprint

main_blueprint = Blueprint('main', __name__, template_folder='templates')

main_blueprint.register_blueprint(user_blueprint, url_prefix='/')
main_blueprint.register_blueprint(damage_blueprint, url_prefix='/damage')
main_blueprint.register_blueprint(document_blueprint, url_prefix='/document')

@main_blueprint.route('/')
def home():
    return render_template('index.html')

@main_blueprint.route('/language/<language>')
def language(language):
    change_lang(lang=language)
    return redirect(request.referrer or url_for('main.home'))

templates/footer.html
<footer>
</footer>

templates/header.html
<header>
    <nav class="navbar is-link" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <div class="navbar-burger" style="background-color: var(--bulma-light); color: var(--bulma-text);" data-target="nav-menu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </div>
        </div>
        <div class="navbar-menu" id="nav-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{{ url_for('main.home') }}">
                    <span class="icon is-small">
                        <i class="fas fa-home"></i>
                    </span>
                    <span>{{ gettext('Home') }}</span>
                </a>
                {% if current_user.is_authenticated and current_user.is_admin() %}
                <a class="navbar-item" href="{{ url_for('main.damage.all') }}">{{ gettext('Damages') }}</a>
                <a class="navbar-item" href="{{ url_for('main.damage.unresolved') }}">{{ gettext('Unresolved') }}</a>
                {% endif %}
            </div>
            <div class="navbar-end">
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link is-arrowless">
                      <span>
                        <span class="icon is-small">
                            <i class="fas fa-globe-americas"></i>
                        </span>
                      </span>
                    </a>
                    <div class="navbar-dropdown">
                      <a class="navbar-item" href="{{ url_for('main.language', language='en') }}">
                        English 🇬🇧
                      </a>
                      <a class="navbar-item" href="{{ url_for('main.language', language='fr') }}">
                        Français 🇫🇷
                      </a>
                    </div>
                </div>
                <div class="navbar-item">
                    <div class="buttons">
                        {% if current_user.is_authenticated %}
                        <a class="button is-light" href="{{ url_for('main.user.profile') }}">
                            <span class="icon is-small">
                                <i class="fas fa-user"></i>
                            </span>
                            <span>{{ gettext('Profile') }}</span>
                        </a>
                        <a class="button is-light is-outlined" href="{{ url_for('main.user.logout') }}">
                            <span class="icon is-small">
                                <i class="fas fa-sign-out-alt"></i>
                            </span>
                            <span>{{ gettext('Log out') }}</span>
                        </a>
                        {% endif %}
                        {% if not current_user.is_authenticated %}
                        <a class="button is-dark" href="{{ url_for('main.user.signup') }}"><strong>{{ gettext('Sign up') }}</strong></a>
                        <a class="button is-light" href="{{ url_for('main.user.login') }}">{{ gettext('Log in') }}</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Add a click event on each of them
        $navbarBurgers.forEach( el => {
            el.addEventListener('click', () => {

                // Get the target from the "data-target" attribute
                const target = el.dataset.target;
                const $target = document.getElementById(target);

                // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                el.classList.toggle('is-active');
                $target.classList.toggle('is-active');

            });
        });
    });
</script>

templates/index.html
{% extends "layout.html" %}
{% block title %}{{ gettext('Hello world!') }}{% endblock %}

{% block content %}
<section class="hero is-medium is-dark">
    <div class="hero-body">
        <h1 class="title">{{ gettext('Welcome to your insurance company') }}</h1>
        <p class="subtitle">{{ gettext('Hello world!') }}</p>
    </div>
</section>
<section class="section">
    <div class="content">
        <h2 class="title">About our company</h2>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut porttitor feugiat magna, at condimentum ex vestibulum sit amet. Aliquam ullamcorper scelerisque justo, at rhoncus nulla condimentum vel. Suspendisse pharetra nisl non urna suscipit molestie. Vestibulum at ipsum dolor. In vitae metus dignissim, aliquet orci et, faucibus elit. Nunc a elit lacus. Nullam elit ex, mollis sed ipsum a, ultricies vulputate est. Nunc mi nulla, ultrices quis ipsum a, consectetur fermentum turpis. Proin at condimentum eros. Ut sed consectetur erat. Fusce posuere et eros vitae iaculis. Nam accumsan ligula odio, in faucibus orci egestas id. Curabitur semper consectetur mi, non hendrerit elit sagittis a. Pellentesque eu purus a nisi varius tincidunt. </p>
    </div>
    <div class="content">
        <h2 class="title">Contact</h2>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut porttitor feugiat magna, at condimentum ex vestibulum sit amet. Aliquam ullamcorper scelerisque justo, at rhoncus nulla condimentum vel. Suspendisse pharetra nisl non urna suscipit molestie. Vestibulum at ipsum dolor. In vitae metus dignissim, aliquet orci et, faucibus elit. Nunc a elit lacus. Nullam elit ex, mollis sed ipsum a, ultricies vulputate est. Nunc mi nulla, ultrices quis ipsum a, consectetur fermentum turpis. Proin at condimentum eros. Ut sed consectetur erat. Fusce posuere et eros vitae iaculis. Nam accumsan ligula odio, in faucibus orci egestas id. Curabitur semper consectetur mi, non hendrerit elit sagittis a. Pellentesque eu purus a nisi varius tincidunt. </p>
    </div>
</section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
    {% include 'header.html' %}

    {% block content %}{% endblock %}
    
    {% include 'footer.html' %}
</body>
</html>

templates/message.html
{% if messages %}
    {% for category, message in messages %}
        {% if category == 'success' %}
        <div class="notification is-success">
            <button class="delete"></button>
            <span class="icon">
                <i class="fas fa-check-circle"></i>
            </span>
            <span>
                {{ message }}
            </span>
        </div>
        {% else %}
        <div class="notification is-danger">
            <button class="delete"></button>
            <span class="icon">
                <i class="fas fa-exclamation-triangle"></i>
            </span>
            <span>
                {{ message }}
            </span>
        </div>
        {% endif %}
    {% endfor %}
    
    <script>
        document.addEventListener('DOMContentLoaded', () => {
        (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
            const $notification = $delete.parentNode;

            $delete.addEventListener('click', () => {
                $notification.parentNode.removeChild($notification);
            });
        });
        });
    </script>
{% endif %}

templates/messages.html
{% if messages %}
    {% for category, message in messages %}
        {% if category == 'success' %}
        <div class="notification is-success">
            <button class="delete"></button>
            <span class="icon">
                <i class="fas fa-check-circle"></i>
            </span>
            <span>
                {{ message }}
            </span>
        </div>
        {% else %}
        <div class="notification is-danger">
            <button class="delete"></button>
            <span class="icon">
                <i class="fas fa-exclamation-triangle"></i>
            </span>
            <span>
                {{ message }}
            </span>
        </div>
        {% endif %}
    {% endfor %}
    <script>
        document.addEventListener('DOMContentLoaded', () => {
        (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
            const $notification = $delete.parentNode;

            $delete.addEventListener('click', () => {
                $notification.parentNode.removeChild($notification);
            });
        });
        });
    </script>
{% endif %}